# Generated by Django 6.0.6 on 2026-06-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ctitle',
            new_name='title',
        ),
    ]
