# Generated by Django 6.0.6 on 2026-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, verbose_name='Name')),
                ('smobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('semail', models.EmailField(max_length=254, verbose_name='Email')),
                ('saddress', models.CharField(verbose_name='Address')),
            ],
        ),
    ]
